// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/sample.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/rickliujh/kickstart-gogrpc/pkg/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "api.v1.Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceScalarProcedure is the fully-qualified name of the Service's Scalar RPC.
	ServiceScalarProcedure = "/api.v1.Service/Scalar"
	// ServiceStreamProcedure is the fully-qualified name of the Service's Stream RPC.
	ServiceStreamProcedure = "/api.v1.Service/Stream"
)

// ServiceClient is a client for the api.v1.Service service.
type ServiceClient interface {
	// Scalar checks the connectivity and response time of the service.
	Scalar(context.Context, *connect.Request[v1.ScalarRequest]) (*connect.Response[v1.ScalarResponse], error)
	// Stream continuously sends and receives response messages.
	// It is useful for scenarios where constant data flow is required.
	Stream(context.Context) *connect.BidiStreamForClient[v1.StreamRequest, v1.StreamResponse]
}

// NewServiceClient constructs a client for the api.v1.Service service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serviceMethods := v1.File_api_v1_sample_proto.Services().ByName("Service").Methods()
	return &serviceClient{
		scalar: connect.NewClient[v1.ScalarRequest, v1.ScalarResponse](
			httpClient,
			baseURL+ServiceScalarProcedure,
			connect.WithSchema(serviceMethods.ByName("Scalar")),
			connect.WithClientOptions(opts...),
		),
		stream: connect.NewClient[v1.StreamRequest, v1.StreamResponse](
			httpClient,
			baseURL+ServiceStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("Stream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	scalar *connect.Client[v1.ScalarRequest, v1.ScalarResponse]
	stream *connect.Client[v1.StreamRequest, v1.StreamResponse]
}

// Scalar calls api.v1.Service.Scalar.
func (c *serviceClient) Scalar(ctx context.Context, req *connect.Request[v1.ScalarRequest]) (*connect.Response[v1.ScalarResponse], error) {
	return c.scalar.CallUnary(ctx, req)
}

// Stream calls api.v1.Service.Stream.
func (c *serviceClient) Stream(ctx context.Context) *connect.BidiStreamForClient[v1.StreamRequest, v1.StreamResponse] {
	return c.stream.CallBidiStream(ctx)
}

// ServiceHandler is an implementation of the api.v1.Service service.
type ServiceHandler interface {
	// Scalar checks the connectivity and response time of the service.
	Scalar(context.Context, *connect.Request[v1.ScalarRequest]) (*connect.Response[v1.ScalarResponse], error)
	// Stream continuously sends and receives response messages.
	// It is useful for scenarios where constant data flow is required.
	Stream(context.Context, *connect.BidiStream[v1.StreamRequest, v1.StreamResponse]) error
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceMethods := v1.File_api_v1_sample_proto.Services().ByName("Service").Methods()
	serviceScalarHandler := connect.NewUnaryHandler(
		ServiceScalarProcedure,
		svc.Scalar,
		connect.WithSchema(serviceMethods.ByName("Scalar")),
		connect.WithHandlerOptions(opts...),
	)
	serviceStreamHandler := connect.NewBidiStreamHandler(
		ServiceStreamProcedure,
		svc.Stream,
		connect.WithSchema(serviceMethods.ByName("Stream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceScalarProcedure:
			serviceScalarHandler.ServeHTTP(w, r)
		case ServiceStreamProcedure:
			serviceStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Scalar(context.Context, *connect.Request[v1.ScalarRequest]) (*connect.Response[v1.ScalarResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.Service.Scalar is not implemented"))
}

func (UnimplementedServiceHandler) Stream(context.Context, *connect.BidiStream[v1.StreamRequest, v1.StreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.Service.Stream is not implemented"))
}
