// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ohlc1m struct {
	ID int64
	H  pgtype.Numeric
	L  pgtype.Numeric
	O  pgtype.Numeric
	C  pgtype.Numeric
	Ts pgtype.Timestamp
}
